### ISSUE TITLE
should QualityOfServiceMetadata be a common element?

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/QoS-capabilities-extension#4]
Both https://github.com/opengeospatial/QoS-capabilities-extension/blob/master/schema/ows-qos-capabilities_wfs.xsd and https://github.com/opengeospatial/QoS-capabilities-extension/blob/master/schema/ows-qos-capabilities_wms.xsd have a `QualityOfServiceMetadata` element in their specific namespace.

Should this be a common element of QoS proper?

**Comment by ilkkarinne** [comment]
Not really: ```qos-wms:QualityOfServiceMetadata``` needs to substitute ```wms:_ExtendedCapabilities``` in order to be included in the WMS capabilities. ```qos-wfs:QualityOfServiceMetadata``` does not need to (and should not to avoid linking to WMS schema)
